config/routes.rb
Rails.application.routes.draw do


devise_scope :user do
    post 'users/sign_up' => 'public/registrations#create'
    post 'users/sign_in' => 'public/sessions#create'
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
end

# # 顧客用
# # URL /users/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
   resource :relationships, only: [:create, :destroy]
  end
  resources :posts, only: [:index, :show, :edit, :update, :destroy] do
   resources :post_comments, only: [:destroy]
  end
end

 scope module: "public" do
      root to: "homes#top"
      get "/users/:id/confirm" => "users#confirm", as: "confirm"
      patch "/users/:id/withdraw" => "users#withdraw", as: "withdraw"
      get "/genre/:id" => "genres#show"
      resources :users, only: [:index, :show, :edit, :update]
      resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resources :post_comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/genre.rb
class Genre < ApplicationRecord

  has_many :posts, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  def index
   @genres = Genre.all
    @genre = Genre.new
  end

  def create
   @genre = Genre.new(genre_params)
   if @genre.save
     redirect_to admin_genres_path(@genre.id)
   else
     @genres = Genre.all
     render :index
   end
  end

  def edit
   @genre = Genre.find(params[:id])
  end

  def update
   @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
     redirect_to admin_genres_path(@genre.id)
    else
     render :edit
    end
  end

 private
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class="row justify-content-md-center">
  <div class="col-3 mt-5">
　　<%= form_with model: [:admin,@genre] do |f| %>
    <div class="form text-center">
    <%= f.label :name, "ジャンルの編集" %>
    <%= f.text_field :name, placeholder: "病種をここに", class: 'form-control' %>
    </div>
    <div>
    <%= f.submit '変更を保存', class: "btn btn-success btn-block mt-2" %>
    </div>
    <% end %>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container mt-5">
  <div class="row justify-content-md-center">
    <div class="col-3 mt-5">
     <%= form_with model: [:admin,@genre] do |f| %>
     <div class="form text-center">
     <%= f.label :name, "ジャンルの追加" %>
     <%= f.text_field :name, placeholder: "病種をここに", class: 'form-control' %>
     </div>
     <div>
     <%= f.submit '新規登録', class: "btn btn-success btn-block mt-2" %>
     </div>
     <% end %>
    </div>

    <div class="row col-4 mt-3">
      <table class="table bg-light">
        <thead>
          <tr>
            <th>ジャンル名</th>
          </th>
        </thead>
        <tbody>
          <%@genres.each do |genre|%>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success" %>
           <% end %>
              </td>
            </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>