config/routes.rb
Rails.application.routes.draw do


devise_scope :user do
    post 'users/sign_up' => 'public/registrations#create'
    post 'users/sign_in' => 'public/sessions#create'
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
end

# # 顧客用
# # URL /users/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
   resource :relationships, only: [:create, :destroy]
  end
  resources :posts, only: [:index, :show, :edit, :update, :destroy] do
   resources :post_comments, only: [:destroy]
  end
end

 scope module: "public" do
      root to: "homes#top"
      get "/users/:id/confirm" => "users#confirm", as: "confirm"
      patch "/users/:id/withdraw" => "users#withdraw", as: "withdraw"
      get "/genre/:id" => "genres#show"
      resources :users, only: [:index, :show, :edit, :update]
      resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resources :post_comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates :comment, presence: true, length:{maximum:100}
end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController

  def destroy
    @post_comment = PostComment.find_by(id: params[:id], post_id: params[:post_id])
    @post = Post.find(params[:post_id])
    if @post_comment.destroy
      redirect_to admin_post_path(@post), notice: "コメントを削除しました。"
    end
  end

end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/views/admin/post_comments/_index.html.erb
<table>
  <tbody>
      <% @post_comments.each do |post_comment| %>
      <tr>
        <td>
          <%= link_to admin_user_path(post_comment.user) do %>
            <%= image_tag post_comment.user.get_profile_image, size: "30x30", class:"profile_image" %><br>
            <div class="comment-user-name"><%= post_comment.user.name %></div>
          <% end %>
        </td>
        <td class="w-100"><%= post_comment.comment %></td>
        <td>
          <div class="text-right">
            <%= link_to "削除", admin_post_post_comment_path(post, post_comment), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger btn-sm" %>
          </div>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>