config/routes.rb
Rails.application.routes.draw do


devise_scope :user do
    post 'users/sign_up' => 'public/registrations#create'
    post 'users/sign_in' => 'public/sessions#create'
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
end

# # 顧客用
# # URL /users/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
   resource :relationships, only: [:create, :destroy]
  end
  resources :posts, only: [:index, :show, :edit, :update, :destroy] do
   resources :post_comments, only: [:destroy]
  end
end

 scope module: "public" do
      root to: "homes#top"
      get "/users/:id/confirm" => "users#confirm", as: "confirm"
      patch "/users/:id/withdraw" => "users#withdraw", as: "withdraw"
      get "/genre/:id" => "genres#show"
      resources :users, only: [:index, :show, :edit, :update]
      resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resources :post_comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy

  enum age: { ten: 0, twenty: 1, thirty: 2, forty: 3, fifty: 4, sixty: 5, seventy: 6, eighty: 7, ninety: 8, other: 9 }

  validates :name, presence:true, length:{maximum:50}
  validates :email, presence:true, length:{maximum:100}

  has_one_attached :profile_image

   def active_for_authentication? #退会物理機能
    super && (is_deleted == false)
   end

  def self.guest #ゲストログイン
    find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
      user.introduction = 'ゲストユーザーです'
    end
  end

  def get_profile_image
    (profile_image.attached?) ? profile_image : 'no_image.jpeg'
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).where(is_deleted: false).page(params[:page]).per(6)
  end

  def show
    @user = User.find(params[:id])
    @q = @user.posts.ransack(params[:q])
    @posts = @q.result(distinct: true).where(user_id: @user).page(params[:page]).per(3)
    @genres = Genre.all
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to admin_user_path(@user)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_users_path
    else
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :age, :introduction, :is_deleted)
  end
end

app/helpers/admin/user_helper.rb
module Admin::UserHelper
end

app/views/admin/users/_info.html.erb
<div class="user-status row no-gutters mt-1 mt-1">
  <div class="col-xs-12 col-md-2 text-center">
    <div class="user-img-area pt-3 pb-3">
      <%= image_tag user.get_profile_image, size:'157x157', class:"profile_image d-block mx-auto" %>
    </div>
  </div>
   <table class="table bg-light">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>名前</th>
            <th>年齢</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
            <th>登録日</th>
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to user.name, admin_user_path(user.id) %></td>
              <td><%= user.age_i18n %></td>
              <td><%= user.email %></td>
              <td>
                <% if user.is_deleted == false %>
              <div class="text-success">有効</div>
            <% else %>
              <div class="text-danger">退会</div>
            <% end %>
              </td>
              <td><%= user.created_at.strftime('%Y/%m/%d') %></td>
            </tr>
        </tbody>
   </table>

    <div class="col-xs-12 col-md-3 text-center mw-100 mx-auto mb-2">
      <%= link_to "ユーザー情報編集", edit_admin_user_path(user), class: "btn btn-success" %>
      <%= link_to "削除する", admin_user_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-danger" %>
    </div>
</div>

app/views/admin/users/_post_index.html.erb
<div class="row">
  <% posts.each do |post| %>
    <div class="col-xs-12 col-md-6 col-lg-4 mt-3">
      <div class = "card border-secondary">
        <div class = "text_omit ml-3 mt-3">
          <%= link_to admin_user_path(post.user) do %>
            <%= image_tag post.user.get_profile_image, size:'40x40', class:"profile_image" %>
            <%= post.user.name %>
          <% end %>
        </div>
        <div class = "card-body">
          <h5 class = "card-title text_omit">
            <%= link_to post.title, admin_post_path(post), class: "post_#{post.id}" %>
          </h5>
          <h6 class = "card-subtitle">
            <div>病種:<%= post.genre.name %>　投稿日:<%= post.created_at.strftime('%Y/%m/%d') %></div>
            <div class="favorite_buttons_<%= post.id %>">
              <i class="fas fa-heart" aria-hidden="true"></i>
              <%= post.favorites.count %>
               <i class="far fa-comment-dots ml-2"></i>
              <%= post.post_comments.count %>
            </div>
        </div>
          </h6>
        </div>
    </div>
  <% end %>
</div>
<div class="mt-3 mr-1 ml-1"><%= paginate posts %></div>

app/views/admin/users/_user.html.erb
<div class="text-center mt-5 mb-5">
  <div class="flame container mt-5 mb-5">
    <div class="form-group">
      <%= search_form_for [:admin,@q] do |f| %>
      <div class="row form-group justify-content-center">
        <div class="search_form col-9 col-md-5 col-xl-4">
          <%= f.search_field :name_cont, placeholder: "ユーザー名検索", class: 'form-control' %>
        </div>
        <div class="form-width col-10 col-md-8 col-xl-6 text-center">
          <%= f.submit "検索", class: "btn btn-success ml-3 mb-1" %>
         </div>
      </div>
    </div>
      <% end %>
    <div class="row search_form">
      <%= sort_link(@q, :created_at, "古い順/新しい順") %>
    </div>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-10">
      <table class="table bg-light">
        <thead>
          <tr>
            <th>会員ID</th>
            <th>名前</th>
            <th>年齢</th>
            <th>メールアドレス</th>
            <th>会員ステータス</th>
          </th>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.id %></td>
              <td><%= link_to user.name, admin_user_path(user.id) %></td>
              <td><%= user.age_i18n %></td>
              <td><%= user.email %></td>
              <td>
                <% if user.is_deleted == false %>
              <div class="text-success">有効</div>
            <% else %>
              <div class="text-danger">退会</div>
            <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-1"></div>
  </div>
  
  <div class="row">
    <div class="mx-auto">
      <%= paginate @users %>
    </div>
  </div>
 
 </div>
</div>

app/views/admin/users/edit.html.erb
<div class="text-center mt-5 mb-5">
  <div class="form-wrapper mb-5">
    <h2 class="form-title mb-5">登録情報編集</h2>

  <%= form_with model: [:admin,@user] do |f| %>
  <%= render 'layouts/error_message', model: f.object %>

    <div class="form-group row">
        <%= f.label "プロフィール画像" %>
        <%= f.file_field :profile_image, class: "form-control-file user_image", accept: 'image/*' %>
    </div>

    <div class="form-group row">
      <label for="customer_name" class="col-sm-2 col-form-label">名前</label>
      <div class="col-sm-10">
        <%= f.text_field :name, class:"col-4" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_address" class="col-sm-2 col-form-label">年齢</label>
      <div class="col-sm-10">
        <%= f.select :age, User.ages.keys.map {|k| [I18n.t("enums.user.age.#{k}"), k]}, class:"col-7" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_telephone_number" class="col-sm-2 col-form-label">自己紹介</label>
      <div class="col-sm-10">
        <%= f.text_field :introduction, class:"col-5" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_email" class="col-sm-2 col-form-label">メールアドレス</label>
      <div class="col-sm-10">
        <%= f.text_field :email, class:"col-4" %>
      </div>
    </div>

    <div class="form-group row">
      <label for="customer_is_active" class="col-sm-2 col-form-label">会員ステータス</label>
      <div class="col-sm-10 d-flex align-items-center">
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_deleted, "false" %>
          有効
        </div>
        <div class="form-check form-check-inline">
          <%= f.radio_button :is_deleted, "true" %>
          退会
        </div>

       <div class="col-sm-3">
        <%= f.submit '編集内容を保存', class: "btn btn-success" %>
       </div>
    </div>
<% end %>
 </div>
 </div>
</div>

app/views/admin/users/index.html.erb
<%= render 'user', users: @users %>

app/views/admin/users/show.html.erb
<div class='main'>
    <div class='mt-5'>
      <%= render 'info', user: @user %>
    </div>

    <div class='flame container mt-5 mb-5'>
      <div class="row search_form">
        <%= search_form_for @q, url: admin_user_path  do |f| %>
          <%= f.search_field :title_cont, placeholder: "投稿タイトル検索", class: "post-form w-100" %>
          <%= f.label :genre_id, "ジャンル" %>
          <%= f.collection_select :genre_id_eq, @genres, :id, :name, include_blank: '指定なし' %>
          <%= f.submit "検索" %>
        <% end %>
      </div>
      <div class = "row search_form">
        <%= sort_link(@q, :created_at, "古い順/新しい順") %>
      </div>
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
          <%= render "post_index", posts: @posts, params_name: "posts_page" %>
        </div>
      </div>
    </div>
</div>