config/routes.rb
Rails.application.routes.draw do


devise_scope :user do
    post 'users/sign_up' => 'public/registrations#create'
    post 'users/sign_in' => 'public/sessions#create'
    post 'users/guest_sign_in' => 'public/sessions#guest_sign_in'
end

# # 顧客用
# # URL /users/sign_in ...
devise_for :users, controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用
# URL /admin/sign_in ...
devise_for :admin, controllers: {
  sessions: "admin/sessions"
}

namespace :admin do
  resources :genres, only: [:index, :create, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update, :destroy] do
   resource :relationships, only: [:create, :destroy]
  end
  resources :posts, only: [:index, :show, :edit, :update, :destroy] do
   resources :post_comments, only: [:destroy]
  end
end

 scope module: "public" do
      root to: "homes#top"
      get "/users/:id/confirm" => "users#confirm", as: "confirm"
      patch "/users/:id/withdraw" => "users#withdraw", as: "withdraw"
      get "/genre/:id" => "genres#show"
      resources :users, only: [:index, :show, :edit, :update]
      resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
        resources :post_comments, only: [:create, :destroy]
        resource :favorites, only: [:create, :destroy]
      end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-xl navbar-dark bg-light shadow-sm">
    <div class="container">
      <% if admin_signed_in? %>
        <a class="navbar-brand">
          <%= image_tag 'icon.jpeg', size: "180x30" %>
        </a>
      <% else %>
        <a class="navbar-brand" href="/">
          <%= image_tag 'icon.jpeg', size: "180x50" %>
        </a>
      <% end %>
      <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
              <li class="nav-item">
                <%= link_to admin_posts_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-clipboard"></i> 投稿一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to admin_users_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-users"></i> ユーザー一覧
                <% end %>
              </li>

             <li class="nav-item">
                <%= link_to admin_genres_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-genderless"></i> ジャンル一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_admin_session_path, method: :delete, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>

            <% elsif user_signed_in? %>
              <li class="nav-item">
                <%= link_to posts_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-clipboard"></i> 投稿一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_post_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-plus-circle"></i> 新規投稿
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to users_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-users"></i> ユーザー一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to user_path(current_user), class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="far fa-address-card"></i> マイページ
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-sign-out-alt"></i> ログアウト
                <% end %>
              </li>

            <% else %>
              <li class="nav-item">
                <%= link_to posts_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-clipboard"></i> 投稿一覧
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_registration_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-plus-square"></i> 新規登録
                <% end %>
              </li>

              <li class="nav-item">
                <%= link_to new_user_session_path, class: "nav-link text-light btn btn-success mr-5 mb-3" do %>
                <i class="fas fa-sign-in-alt"></i> ログイン
                <% end %>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
  </nav>

app/views/layouts/_notice.html.erb
<% if notice %>
 <p id="notice" class="alert alert-success m-0 text-center"><%= notice %></p>
<% end %>

<% if alert %>
 <p id="notice" class="alert alert-danger m-0 text-center"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Live_community</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="footerFixed">

      <header>
        <%= render 'layouts/header' %>
      </header>

      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <%= yield %>

      <footer>
        <div class="text-center web-copyright pt-3 pb-3">
          Copyright © live-community
        </div>
      </footer>

    </div>

  </body>
</html>